/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author beto_
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraStatus = new javax.swing.JPanel();
        lblBarraUsuario = new javax.swing.JLabel();
        lblBarraPerfil = new javax.swing.JLabel();
        lblBarraDatadia = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadCliente = new javax.swing.JMenuItem();
        menCadProfissao = new javax.swing.JMenuItem();
        menCadFornecedor = new javax.swing.JMenuItem();
        menCadVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menCadProdutos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menCadUsuario = new javax.swing.JMenuItem();
        menMovimento = new javax.swing.JMenu();
        menMovPedido = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menMovCompras = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menMovEstoque = new javax.swing.JMenuItem();
        menRelatorios = new javax.swing.JMenu();
        menRelClientes = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menAjuHelp = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menAjuSair = new javax.swing.JMenuItem();
        menSobre = new javax.swing.JMenu();
        menSobreSobre = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Cartuchos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlBarraStatus.setBackground(new java.awt.Color(153, 255, 153));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 51, 255));
        lblUsuario.setText("Usuario");

        lblPerfil.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(0, 51, 255));
        lblPerfil.setText("Perfil");

        lblData.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 51, 255));
        lblData.setText("Data");

        javax.swing.GroupLayout pnlBarraStatusLayout = new javax.swing.GroupLayout(pnlBarraStatus);
        pnlBarraStatus.setLayout(pnlBarraStatusLayout);
        pnlBarraStatusLayout.setHorizontalGroup(
            pnlBarraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBarraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBarraPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBarraDatadia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlBarraStatusLayout.setVerticalGroup(
            pnlBarraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBarraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBarraPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBarraDatadia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBarraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsuario)
                        .addComponent(lblPerfil)
                        .addComponent(lblData)))
                .addContainerGap())
        );

        menCad.setText("Cadastros");

        menCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadCliente.setText("Clientes");
        menCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadClienteActionPerformed(evt);
            }
        });
        menCad.add(menCadCliente);

        menCadProfissao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadProfissao.setText("Profissão");
        menCadProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadProfissaoActionPerformed(evt);
            }
        });
        menCad.add(menCadProfissao);

        menCadFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadFornecedor.setText("Fornecedor");
        menCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadFornecedorActionPerformed(evt);
            }
        });
        menCad.add(menCadFornecedor);

        menCadVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadVendedor.setText("Vendedor");
        menCadVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadVendedorActionPerformed(evt);
            }
        });
        menCad.add(menCadVendedor);
        menCad.add(jSeparator1);

        menCadProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadProdutos.setText("Produtos");
        menCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadProdutosActionPerformed(evt);
            }
        });
        menCad.add(menCadProdutos);
        menCad.add(jSeparator2);

        menCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadUsuario.setText("Usuário");
        menCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuarioActionPerformed(evt);
            }
        });
        menCad.add(menCadUsuario);

        Menu.add(menCad);

        menMovimento.setText("Movimento");

        menMovPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menMovPedido.setText("Pedidos");
        menMovPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMovPedidoActionPerformed(evt);
            }
        });
        menMovimento.add(menMovPedido);
        menMovimento.add(jSeparator3);

        menMovCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menMovCompras.setText("Compras");
        menMovimento.add(menMovCompras);
        menMovimento.add(jSeparator4);

        menMovEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menMovEstoque.setText("Estoque");
        menMovimento.add(menMovEstoque);

        Menu.add(menMovimento);

        menRelatorios.setText("Relatorios");

        menRelClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelClientes.setText("Clientes");
        menRelatorios.add(menRelClientes);

        Menu.add(menRelatorios);

        menAjuda.setText("Ajuda");

        menAjuHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menAjuHelp.setText("Help");
        menAjuda.add(menAjuHelp);
        menAjuda.add(jSeparator6);

        menAjuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menAjuSair.setText("Sair");
        menAjuda.add(menAjuSair);

        Menu.add(menAjuda);

        menSobre.setText("Sobre");

        menSobreSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menSobreSobre.setText("Sobre");
        menSobre.add(menSobreSobre);
        menSobre.add(jSeparator5);

        Menu.add(menSobre);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarraStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 399, Short.MAX_VALUE)
                .addComponent(pnlBarraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(814, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadFornecedorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        long Date;
        Date datadia = new Date();
        DateFormat formatador = 
                DateFormat.getDateInstance(DateFormat.SHORT);
        lblBarraDatadia.setText(formatador.format(datadia));
        
    }//GEN-LAST:event_formWindowActivated

    private void menCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuarioActionPerformed
        // TODO add your handling code here:
       Tela_Usuario usuario = new Tela_Usuario();
        usuario.setVisible(true);
    }//GEN-LAST:event_menCadUsuarioActionPerformed

    private void menCadProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadProfissaoActionPerformed
        // TODO add your handling code here:
        TelaProfissao profissao = new TelaProfissao();
        profissao.setVisible(true);
    }//GEN-LAST:event_menCadProfissaoActionPerformed

    private void menCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadClienteActionPerformed
        // TODO add your handling code here:
        TelaCliente clientes = new TelaCliente();
        clientes.setVisible(true);
    }//GEN-LAST:event_menCadClienteActionPerformed

    private void menCadVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadVendedorActionPerformed
        // TODO add your handling code here:
        Tela_Vendedor vendedor = new Tela_Vendedor();
        vendedor.setVisible(true);
    }//GEN-LAST:event_menCadVendedorActionPerformed

    private void menCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadProdutosActionPerformed
        // TODO add your handling code here:
        TelaProduto produto = new TelaProduto();
        produto.setVisible(true);
    }//GEN-LAST:event_menCadProdutosActionPerformed

    private void menMovPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMovPedidoActionPerformed
        // TODO add your handling code here:
        TelaPedidos produto = new TelaPedidos();
        produto.setVisible(true);
    }//GEN-LAST:event_menMovPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    public static javax.swing.JLabel lblBarraDatadia;
    public static javax.swing.JLabel lblBarraPerfil;
    public static javax.swing.JLabel lblBarraUsuario;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menAjuHelp;
    private javax.swing.JMenuItem menAjuSair;
    private javax.swing.JMenu menAjuda;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadCliente;
    private javax.swing.JMenuItem menCadFornecedor;
    private javax.swing.JMenuItem menCadProdutos;
    private javax.swing.JMenuItem menCadProfissao;
    public static javax.swing.JMenuItem menCadUsuario;
    private javax.swing.JMenuItem menCadVendedor;
    private javax.swing.JMenuItem menMovCompras;
    private javax.swing.JMenuItem menMovEstoque;
    private javax.swing.JMenuItem menMovPedido;
    private javax.swing.JMenu menMovimento;
    private javax.swing.JMenuItem menRelClientes;
    public static javax.swing.JMenu menRelatorios;
    private javax.swing.JMenu menSobre;
    private javax.swing.JMenuItem menSobreSobre;
    private javax.swing.JPanel pnlBarraStatus;
    // End of variables declaration//GEN-END:variables
}
